#!/usr/bin/env python3
"""GCTA regression test framework.

Compares build/gcta64 output against truth files generated by the reference
binary.  Run from the GCTA root directory (or anywhere — the script relocates
to it automatically):

    python tests/run_tests.py

Truth files are generated on demand (only when missing) using TRUTH_BINARY.
Query files are always regenerated from the current build.

Output format (.mlma): 9-column TSV
    Chr  SNP  bp  A1  A2  Freq  b  se  p

Comparison strategy:
    Columns 0–5  (Chr, SNP, bp, A1, A2, Freq): exact string match
    Columns 6–8  (b, se, p):                   |truth - query| <= ABS_TOL
"""

import os
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

QUERY_BINARY = "build/gcta64"
TRUTH_BINARY = "../gcta-1.95.1-macOS-arm64/bin/gcta64"

ABS_TOL = 1e-5

# Column layout (0-indexed)
COL_NAMES  = ["Chr", "SNP", "bp", "A1", "A2", "Freq", "b", "se", "p"]
EXACT_COLS = list(range(6))   # Chr … Freq — exact string comparison
FLOAT_COLS = [6, 7, 8]        # b, se, p  — float comparison with ABS_TOL

# ---------------------------------------------------------------------------
# Test-case definitions
# ---------------------------------------------------------------------------

@dataclass
class TestCase:
    name: str
    truth_cmds: List[List[str]]   # commands needed to produce truth_file
    query_cmds: List[List[str]]   # commands needed to produce query_file
    truth_file: str
    query_file: str


TEST_CASES: List[TestCase] = [

    # ------------------------------------------------------------------
    # Standard one-step MLMA (bfile input)
    # ------------------------------------------------------------------
    TestCase(
        name="bfile_onestep",
        truth_cmds=[
            [TRUTH_BINARY,
             "--threads", "8",
             "--bfile",  "tests/data/test",
             "--grm",    "tests/data/test",
             "--pheno",  "tests/data/test.phen",
             "--mlma",
             "--out",    "tests/truth/bfile_onestep"],
        ],
        query_cmds=[
            [QUERY_BINARY,
             "--threads", "8",
             "--bfile",  "tests/data/test",
             "--grm",    "tests/data/test",
             "--pheno",  "tests/data/test.phen",
             "--mlma",
             "--out",    "tests/query/bfile_onestep"],
        ],
        truth_file="tests/truth/bfile_onestep.mlma",
        query_file="tests/query/bfile_onestep.mlma",
    ),

    # ------------------------------------------------------------------
    # Two-step MLMA: save-reml then load-reml (bfile input).
    # The load-reml step appends "_B" to the output stem.
    # Truth is the same reference one-step output: saving and reloading
    # REML state must reproduce identical association results.
    # ------------------------------------------------------------------
    TestCase(
        name="bfile_twostep",
        truth_cmds=[
            # Reuse the one-step truth (same data, should be identical numerically).
            # This generates tests/truth/bfile_onestep.mlma if not already present.
            [TRUTH_BINARY,
             "--threads", "8",
             "--bfile",  "tests/data/test",
             "--grm",    "tests/data/test",
             "--pheno",  "tests/data/test.phen",
             "--mlma",
             "--out",    "tests/truth/bfile_onestep"],
        ],
        query_cmds=[
            [QUERY_BINARY,
             "--threads", "8",
             "--bfile",  "tests/data/test",
             "--grm",    "tests/data/test",
             "--pheno",  "tests/data/test.phen",
             "--mlma",
             "--save-reml", "tests/query/bfile_twostep.reml.gz",
             "--out",    "tests/query/bfile_twostep"],
            [QUERY_BINARY,
             "--threads", "8",
             "--bfile",  "tests/data/test",
             "--grm",    "tests/data/test",
             "--pheno",  "tests/data/test.phen",
             "--mlma",
             "--load-reml", "tests/query/bfile_twostep.reml.gz",
             "--out",    "tests/query/bfile_twostep"],
        ],
        # truth is the one-step reference; query is the _B (load-reml) output
        truth_file="tests/truth/bfile_onestep.mlma",
        query_file="tests/query/bfile_twostep_B.mlma",
    ),

    # ------------------------------------------------------------------
    # One-step MLMA with MACH dosage input
    # ------------------------------------------------------------------
    TestCase(
        name="dosage_onestep",
        truth_cmds=[
            [TRUTH_BINARY,
             "--dosage-mach-gz",
             "tests/data/dosage/test.mldose.gz",
             "tests/data/dosage/test.mlinfo.gz",
             "--grm",   "tests/data/dosage/test",
             "--pheno", "tests/data/dosage/test.phen",
             "--mlma",
             "--out",   "tests/truth/dosage_onestep"],
        ],
        query_cmds=[
            [QUERY_BINARY,
             "--dosage-mach-gz",
             "tests/data/dosage/test.mldose.gz",
             "tests/data/dosage/test.mlinfo.gz",
             "--grm",   "tests/data/dosage/test",
             "--pheno", "tests/data/dosage/test.phen",
             "--mlma",
             "--out",   "tests/query/dosage_onestep"],
        ],
        truth_file="tests/truth/dosage_onestep.mlma",
        query_file="tests/query/dosage_onestep.mlma",
    ),
]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _run_cmd(cmd: List[str]) -> None:
    """Run *cmd*, raising RuntimeError on non-zero exit."""
    print(f"    $ {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        stderr_tail = (result.stderr or "")[-2000:]
        raise RuntimeError(
            f"Command exited with code {result.returncode}:\n{stderr_tail}"
        )


def _compare_mlma(
    truth_path: str, query_path: str, abs_tol: float
) -> List[str]:
    """Compare two .mlma files; return a list of failure messages (empty = pass)."""
    failures: List[str] = []

    with open(truth_path) as tf, open(query_path) as qf:
        truth_lines = tf.readlines()
        query_lines = qf.readlines()

    if len(truth_lines) != len(query_lines):
        failures.append(
            f"Row count mismatch: truth={len(truth_lines)} query={len(query_lines)}"
        )
        return failures

    for line_num, (tl, ql) in enumerate(zip(truth_lines, query_lines)):
        t_cols = tl.rstrip("\n").split("\t")
        q_cols = ql.rstrip("\n").split("\t")

        if len(t_cols) != 9:
            failures.append(
                f"Line {line_num + 1}: truth has {len(t_cols)} columns (expected 9)"
            )
            continue
        if len(q_cols) != 9:
            failures.append(
                f"Line {line_num + 1}: query has {len(q_cols)} columns (expected 9)"
            )
            continue

        # Header row: exact full match
        if line_num == 0:
            if t_cols != q_cols:
                failures.append(
                    f"Header mismatch:\n  truth: {t_cols}\n  query: {q_cols}"
                )
            continue

        snp_id = t_cols[1]

        # Exact-match columns (Chr … Freq)
        for col_idx in EXACT_COLS:
            if t_cols[col_idx] != q_cols[col_idx]:
                failures.append(
                    f"Line {line_num + 1} SNP={snp_id} "
                    f"col={COL_NAMES[col_idx]}: "
                    f"exact mismatch truth={t_cols[col_idx]!r} "
                    f"query={q_cols[col_idx]!r}"
                )

        # Float columns (b, se, p) with absolute tolerance
        for col_idx in FLOAT_COLS:
            try:
                t_val = float(t_cols[col_idx])
                q_val = float(q_cols[col_idx])
            except ValueError as exc:
                failures.append(
                    f"Line {line_num + 1} SNP={snp_id} "
                    f"col={COL_NAMES[col_idx]}: "
                    f"could not parse as float — {exc}"
                )
                continue

            diff = abs(t_val - q_val)
            if diff > abs_tol:
                failures.append(
                    f"Line {line_num + 1} SNP={snp_id} "
                    f"col={COL_NAMES[col_idx]}: "
                    f"|{t_val} - {q_val}| = {diff:.3e} > tol={abs_tol:.0e}"
                )

    return failures


# ---------------------------------------------------------------------------
# Per-test runner
# ---------------------------------------------------------------------------

def run_test(tc: TestCase) -> bool:
    """Execute one test case.  Returns True on pass."""
    print(f"\n{'=' * 60}")
    print(f"TEST: {tc.name}")
    print(f"{'=' * 60}")

    # ---- truth generation (only when missing) ----
    if Path(tc.truth_file).exists():
        print(f"  [truth] using existing file: {tc.truth_file}")
    else:
        truth_binary = tc.truth_cmds[0][0] if tc.truth_cmds else TRUTH_BINARY
        if not Path(truth_binary).exists():
            print(
                f"  SKIP: truth file missing and truth binary not found: "
                f"{truth_binary}"
            )
            return False

        print(f"  [truth] generating: {tc.truth_file}")
        Path(tc.truth_file).parent.mkdir(parents=True, exist_ok=True)
        try:
            for cmd in tc.truth_cmds:
                _run_cmd(cmd)
        except RuntimeError as exc:
            print(f"  SKIP: truth generation failed — {exc}")
            return False

    if not Path(tc.truth_file).exists():
        print(f"  SKIP: truth file still missing after generation: {tc.truth_file}")
        return False

    # ---- query execution ----
    if not Path(QUERY_BINARY).exists():
        print(f"  FAIL: query binary not found: {QUERY_BINARY}")
        return False

    print(f"  [query] running {len(tc.query_cmds)} command(s) ...")
    Path(tc.query_file).parent.mkdir(parents=True, exist_ok=True)
    try:
        for cmd in tc.query_cmds:
            _run_cmd(cmd)
    except RuntimeError as exc:
        print(f"  FAIL: query execution failed — {exc}")
        return False

    if not Path(tc.query_file).exists():
        print(f"  FAIL: expected output not produced: {tc.query_file}")
        return False

    # ---- comparison ----
    print(
        f"  [compare] {tc.query_file} vs {tc.truth_file}  "
        f"(exact: cols 0–5 | abs_tol={ABS_TOL:.0e}: cols 6–8)"
    )
    failures = _compare_mlma(tc.truth_file, tc.query_file, ABS_TOL)

    if failures:
        max_shown = 20
        print(f"  FAIL: {len(failures)} difference(s) found:")
        for msg in failures[:max_shown]:
            print(f"    {msg}")
        if len(failures) > max_shown:
            print(f"    ... and {len(failures) - max_shown} more")
        return False

    print("  PASS")
    return True


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> int:
    # Always run relative to the GCTA root (parent of this script's directory)
    root = Path(__file__).resolve().parent.parent
    os.chdir(root)
    print(f"Working directory: {root}")

    results: dict[str, bool] = {}
    for tc in TEST_CASES:
        results[tc.name] = run_test(tc)

    print(f"\n{'=' * 60}")
    print("SUMMARY")
    print(f"{'=' * 60}")
    all_passed = True
    for name, passed in results.items():
        status = "PASS" if passed else "FAIL"
        print(f"  {status}  {name}")
        if not passed:
            all_passed = False

    return 0 if all_passed else 1


if __name__ == "__main__":
    sys.exit(main())
